server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bidhub_account}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:bidhub}
    password: ${DB_PASSWORD:bidhub}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.bidhub: INFO
