server:
  port: 8081

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

bidhub:
  jwt:
    secret: ${JWT_SECRET}
  internal:
    api-token: ${INTERNAL_API_TOKEN}

logging:
  level:
    com.bidhub: INFO
