server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:payment_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.bidhub: DEBUG
